// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Helpers;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210429122759_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CustomAutoHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Changed")
                        .HasColumnType("character varying(2048)")
                        .HasMaxLength(2048);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("CustomAutoHistory");
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("Banned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordReset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Verified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptTerms = true,
                            Created = new DateTimeOffset(new DateTime(1950, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Email = "a@a.com",
                            FirstName = "Olcay",
                            LastName = "Bayram",
                            Role = 0,
                            Verified = new DateTimeOffset(new DateTime(1950, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdoptedById")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(1500)")
                        .HasMaxLength(1500);

                    b.Property<int>("FromWhere")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("PetStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PetType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Published")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AdoptedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RaceId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            Age = 1,
                            CityId = 34,
                            Created = new DateTimeOffset(new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedById = 1,
                            Description = "Evde anne sütüyle büyüyen oyuncu",
                            FromWhere = 3,
                            Gender = 1,
                            Name = "Mişa",
                            PetStatus = 1,
                            PetType = 1,
                            Published = new DateTimeOffset(new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            RaceId = 43,
                            Size = 1,
                            Title = "Norveç orman melezi bebek"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abyssinian",
                            PetType = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "American Bobtail",
                            PetType = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "American Curl",
                            PetType = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "American Keuda",
                            PetType = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "American Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "American Wirehair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ankara Kedisi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Australian Mist",
                            PetType = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Balinese",
                            PetType = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bengal",
                            PetType = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Birman",
                            PetType = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bombay",
                            PetType = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Brazilian Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "British Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Burmese",
                            PetType = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Burmilla (Silver Burmese)",
                            PetType = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Californian Spangled",
                            PetType = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Chartreux",
                            PetType = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chinchilla",
                            PetType = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Colorpoint Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cornish Rex",
                            PetType = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cymric",
                            PetType = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Devon Rex",
                            PetType = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Egyptian Maular",
                            PetType = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "European Burmese",
                            PetType = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "European Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Exotic Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 28,
                            Name = "Havana Brown",
                            PetType = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Himalayan",
                            PetType = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Honey Bear",
                            PetType = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "İran Kedisi (Persian)",
                            PetType = 1
                        },
                        new
                        {
                            Id = 32,
                            Name = "Japon Bobtail",
                            PetType = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Javanese",
                            PetType = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Kashmir ",
                            PetType = 1
                        },
                        new
                        {
                            Id = 35,
                            Name = "Korat",
                            PetType = 1
                        },
                        new
                        {
                            Id = 36,
                            Name = "Laperm",
                            PetType = 1
                        },
                        new
                        {
                            Id = 37,
                            Name = "Maine Coon",
                            PetType = 1
                        },
                        new
                        {
                            Id = 38,
                            Name = "Manx",
                            PetType = 1
                        },
                        new
                        {
                            Id = 39,
                            Name = "Mavi Rus",
                            PetType = 1
                        },
                        new
                        {
                            Id = 40,
                            Name = "Mojave Spotted (Mojave çöl Kedisi)",
                            PetType = 1
                        },
                        new
                        {
                            Id = 41,
                            Name = "Munchkin",
                            PetType = 1
                        },
                        new
                        {
                            Id = 42,
                            Name = "Nebelung",
                            PetType = 1
                        },
                        new
                        {
                            Id = 43,
                            Name = "Norveç Ormanı",
                            PetType = 1
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ocicat",
                            PetType = 1
                        },
                        new
                        {
                            Id = 45,
                            Name = "Oriental Longhair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 46,
                            Name = "Oriental Shorthair",
                            PetType = 1
                        },
                        new
                        {
                            Id = 47,
                            Name = "Pixie Bob",
                            PetType = 1
                        },
                        new
                        {
                            Id = 48,
                            Name = "Ragamuffin",
                            PetType = 1
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ragdoll",
                            PetType = 1
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sarman",
                            PetType = 1
                        },
                        new
                        {
                            Id = 51,
                            Name = "Savannah",
                            PetType = 1
                        },
                        new
                        {
                            Id = 52,
                            Name = "Scottish Fold",
                            PetType = 1
                        },
                        new
                        {
                            Id = 53,
                            Name = "Selkirk Rex",
                            PetType = 1
                        },
                        new
                        {
                            Id = 54,
                            Name = "Sibirya Kedisi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 55,
                            Name = "Singapura",
                            PetType = 1
                        },
                        new
                        {
                            Id = 56,
                            Name = "Siyam Kedisi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 57,
                            Name = "Snowshoe (Karayak)",
                            PetType = 1
                        },
                        new
                        {
                            Id = 58,
                            Name = "Soke",
                            PetType = 1
                        },
                        new
                        {
                            Id = 59,
                            Name = "Somali",
                            PetType = 1
                        },
                        new
                        {
                            Id = 60,
                            Name = "Sphynx",
                            PetType = 1
                        },
                        new
                        {
                            Id = 61,
                            Name = "Tekir Kedi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 62,
                            Name = "Tiffanie",
                            PetType = 1
                        },
                        new
                        {
                            Id = 63,
                            Name = "Tiffany/Chantilly",
                            PetType = 1
                        },
                        new
                        {
                            Id = 64,
                            Name = "Tonkinese",
                            PetType = 1
                        },
                        new
                        {
                            Id = 65,
                            Name = "Tuxedo (Smokin) Kedi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 66,
                            Name = "Van Kedisi",
                            PetType = 1
                        },
                        new
                        {
                            Id = 67,
                            Name = "York Chocolate",
                            PetType = 1
                        },
                        new
                        {
                            Id = 68,
                            Name = "Affenpinscher",
                            PetType = 2
                        },
                        new
                        {
                            Id = 69,
                            Name = "Afgan Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 70,
                            Name = "Aidi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ainu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 72,
                            Name = "Airedale Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 73,
                            Name = "Akbaş",
                            PetType = 2
                        },
                        new
                        {
                            Id = 74,
                            Name = "Akita İnu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 75,
                            Name = "Aksaray Malaklısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 76,
                            Name = "Alabay (Alabai)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 77,
                            Name = "Alaskan Malamute",
                            PetType = 2
                        },
                        new
                        {
                            Id = 78,
                            Name = "Alman Av Terrieri",
                            PetType = 2
                        },
                        new
                        {
                            Id = 79,
                            Name = "Alman Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 80,
                            Name = "Alman Kalın Tüylü Pointer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 81,
                            Name = "Alman Kısa Tüylü Pointer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 82,
                            Name = "Alman Spanieli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 83,
                            Name = "Alpine Dachsbracke",
                            PetType = 2
                        },
                        new
                        {
                            Id = 84,
                            Name = "Amerikan Bulldog",
                            PetType = 2
                        },
                        new
                        {
                            Id = 85,
                            Name = "Amerikan Cocker Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 86,
                            Name = "Amerikan Eskimo",
                            PetType = 2
                        },
                        new
                        {
                            Id = 87,
                            Name = "Amerikan Pitbull Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 88,
                            Name = "Amerikan Staffordshire Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 89,
                            Name = "Amerikan Su Spanieli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 90,
                            Name = "Amerikan Tilki Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 91,
                            Name = "Amerikan Tüysüz Terrieri",
                            PetType = 2
                        },
                        new
                        {
                            Id = 92,
                            Name = "Amerikan Yerli Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 93,
                            Name = "Appenzell Dağ Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 94,
                            Name = "Ariegeois",
                            PetType = 2
                        },
                        new
                        {
                            Id = 95,
                            Name = "Avustralya Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 96,
                            Name = "Avustralya Sığır Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 97,
                            Name = "Avustralya Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 98,
                            Name = "Avustralyalı Kelpie",
                            PetType = 2
                        },
                        new
                        {
                            Id = 99,
                            Name = "Avusturya Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 100,
                            Name = "Avusturyalı Pinscher",
                            PetType = 2
                        },
                        new
                        {
                            Id = 101,
                            Name = "Bandogge Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 102,
                            Name = "Basenji",
                            PetType = 2
                        },
                        new
                        {
                            Id = 103,
                            Name = "Basset Hound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 104,
                            Name = "Bavyera Dağ Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 105,
                            Name = "Beagle",
                            PetType = 2
                        },
                        new
                        {
                            Id = 106,
                            Name = "Beauceron",
                            PetType = 2
                        },
                        new
                        {
                            Id = 107,
                            Name = "Bedlington Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 108,
                            Name = "Belçika Groenendael",
                            PetType = 2
                        },
                        new
                        {
                            Id = 109,
                            Name = "Belçika Laekenois",
                            PetType = 2
                        },
                        new
                        {
                            Id = 110,
                            Name = "Belçika Malinois",
                            PetType = 2
                        },
                        new
                        {
                            Id = 111,
                            Name = "Belçika Tervuren",
                            PetType = 2
                        },
                        new
                        {
                            Id = 112,
                            Name = "Bergamasco",
                            PetType = 2
                        },
                        new
                        {
                            Id = 113,
                            Name = "Bernese Dağ Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 114,
                            Name = "Bichon Frise",
                            PetType = 2
                        },
                        new
                        {
                            Id = 115,
                            Name = "Bichon Havanese",
                            PetType = 2
                        },
                        new
                        {
                            Id = 116,
                            Name = "Billy",
                            PetType = 2
                        },
                        new
                        {
                            Id = 117,
                            Name = "Bloodhound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 118,
                            Name = "Border Collie",
                            PetType = 2
                        },
                        new
                        {
                            Id = 119,
                            Name = "Border Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 120,
                            Name = "Borzoi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 121,
                            Name = "Boston Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 122,
                            Name = "Bouvier des Ardennes",
                            PetType = 2
                        },
                        new
                        {
                            Id = 123,
                            Name = "Bouvier des Flandres",
                            PetType = 2
                        },
                        new
                        {
                            Id = 124,
                            Name = "Boxer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 125,
                            Name = "Brezilya Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 126,
                            Name = "Briard",
                            PetType = 2
                        },
                        new
                        {
                            Id = 127,
                            Name = "Brittany",
                            PetType = 2
                        },
                        new
                        {
                            Id = 128,
                            Name = "Brüksel Griffonu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 129,
                            Name = "Bull Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 130,
                            Name = "Bullmastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 131,
                            Name = "Büyük İsveç Dağ Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 132,
                            Name = "Cairn Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 133,
                            Name = "Canaan Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 134,
                            Name = "Cane Corso Italiano",
                            PetType = 2
                        },
                        new
                        {
                            Id = 135,
                            Name = "Cao da Serra da Estrela",
                            PetType = 2
                        },
                        new
                        {
                            Id = 136,
                            Name = "Cao de Castro Laboreiro",
                            PetType = 2
                        },
                        new
                        {
                            Id = 137,
                            Name = "Cao de Serra de Aires",
                            PetType = 2
                        },
                        new
                        {
                            Id = 138,
                            Name = "Cardigan Welsh Corgi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 139,
                            Name = "Catahoula Leopar Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 140,
                            Name = "Cavalier King Charles Spanieli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 141,
                            Name = "Cesky Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 142,
                            Name = "Chesapeake Bay Retriever",
                            PetType = 2
                        },
                        new
                        {
                            Id = 143,
                            Name = "Chiens Francaises",
                            PetType = 2
                        },
                        new
                        {
                            Id = 144,
                            Name = "Chihuahua",
                            PetType = 2
                        },
                        new
                        {
                            Id = 145,
                            Name = "Chow Chow (çin Aslanı)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 146,
                            Name = "Clumber Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 147,
                            Name = "Collie",
                            PetType = 2
                        },
                        new
                        {
                            Id = 148,
                            Name = "Coton De Tulear",
                            PetType = 2
                        },
                        new
                        {
                            Id = 149,
                            Name = "Curly Coated Retriever",
                            PetType = 2
                        },
                        new
                        {
                            Id = 150,
                            Name = "Çatalburun",
                            PetType = 2
                        },
                        new
                        {
                            Id = 151,
                            Name = "Çin Creste Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 152,
                            Name = "Çin Shar Pei",
                            PetType = 2
                        },
                        new
                        {
                            Id = 153,
                            Name = "Dachshund (Sosis)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 154,
                            Name = "Dalmatian",
                            PetType = 2
                        },
                        new
                        {
                            Id = 155,
                            Name = "Dandie Dinmont Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 156,
                            Name = "Dev Schnauzer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 157,
                            Name = "Doberman Pinscher",
                            PetType = 2
                        },
                        new
                        {
                            Id = 158,
                            Name = "Dogo Arjantin",
                            PetType = 2
                        },
                        new
                        {
                            Id = 159,
                            Name = "Entlebucher",
                            PetType = 2
                        },
                        new
                        {
                            Id = 160,
                            Name = "Eskimo Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 161,
                            Name = "Field Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 162,
                            Name = "Fin Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 163,
                            Name = "Finnish Spitz",
                            PetType = 2
                        },
                        new
                        {
                            Id = 164,
                            Name = "Flat Coated Retriever",
                            PetType = 2
                        },
                        new
                        {
                            Id = 165,
                            Name = "Fox Terrier (Smooth)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 166,
                            Name = "Fox Terrier (Wire)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 167,
                            Name = "Fransız Bulldog",
                            PetType = 2
                        },
                        new
                        {
                            Id = 168,
                            Name = "Fransız Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 169,
                            Name = "Glen of Imaal Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 170,
                            Name = "Golden Retriever",
                            PetType = 2
                        },
                        new
                        {
                            Id = 171,
                            Name = "Gordon Setter",
                            PetType = 2
                        },
                        new
                        {
                            Id = 172,
                            Name = "Grand Bleu de Gascogne",
                            PetType = 2
                        },
                        new
                        {
                            Id = 173,
                            Name = "Grand Gascon Saintongeois",
                            PetType = 2
                        },
                        new
                        {
                            Id = 174,
                            Name = "Great Dane (Danua)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 175,
                            Name = "Great Phyrenees",
                            PetType = 2
                        },
                        new
                        {
                            Id = 176,
                            Name = "Greyhound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 177,
                            Name = "Grönland Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 178,
                            Name = "Hanover Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 179,
                            Name = "Harrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 180,
                            Name = "Hırvat Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 181,
                            Name = "Hollanda Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 182,
                            Name = "Hovawart",
                            PetType = 2
                        },
                        new
                        {
                            Id = 183,
                            Name = "Ibizan Hound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 184,
                            Name = "İlirya çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 185,
                            Name = "İngiliz Bulldog",
                            PetType = 2
                        },
                        new
                        {
                            Id = 186,
                            Name = "İngiliz Cocker Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 187,
                            Name = "İngiliz Setter",
                            PetType = 2
                        },
                        new
                        {
                            Id = 188,
                            Name = "İngiliz Springer Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 189,
                            Name = "İngiliz Tilki Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 190,
                            Name = "İrlandalı Kurt Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 191,
                            Name = "İrlandalı Setter",
                            PetType = 2
                        },
                        new
                        {
                            Id = 192,
                            Name = "İrlandalı Su Spanieli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 193,
                            Name = "İrlandalı Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 194,
                            Name = "İskoç Geyik Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 195,
                            Name = "İskoç Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 196,
                            Name = "İspanyol Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 197,
                            Name = "İsveç çoban köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 198,
                            Name = "İsveç Geyik Avcısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 199,
                            Name = "İtalyan Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 200,
                            Name = "İzlanda Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 201,
                            Name = "Jack Russell Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 202,
                            Name = "Japon Chin",
                            PetType = 2
                        },
                        new
                        {
                            Id = 203,
                            Name = "Kangal",
                            PetType = 2
                        },
                        new
                        {
                            Id = 204,
                            Name = "Karelya Ayı Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 205,
                            Name = "Kars Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 206,
                            Name = "Karst Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 207,
                            Name = "Katalan Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 208,
                            Name = "Keeshond",
                            PetType = 2
                        },
                        new
                        {
                            Id = 209,
                            Name = "Kerry Blue Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 210,
                            Name = "King Charles Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 211,
                            Name = "Komondor",
                            PetType = 2
                        },
                        new
                        {
                            Id = 212,
                            Name = "Kuvasz",
                            PetType = 2
                        },
                        new
                        {
                            Id = 213,
                            Name = "Kyüshü",
                            PetType = 2
                        },
                        new
                        {
                            Id = 214,
                            Name = "Labrador Retriever",
                            PetType = 2
                        },
                        new
                        {
                            Id = 215,
                            Name = "Lakeland Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 216,
                            Name = "Landseer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 217,
                            Name = "Lapphund",
                            PetType = 2
                        },
                        new
                        {
                            Id = 218,
                            Name = "Lapponian Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 219,
                            Name = "Leonberger",
                            PetType = 2
                        },
                        new
                        {
                            Id = 220,
                            Name = "Lhasa Apso",
                            PetType = 2
                        },
                        new
                        {
                            Id = 221,
                            Name = "Lowchen",
                            PetType = 2
                        },
                        new
                        {
                            Id = 222,
                            Name = "Maltese",
                            PetType = 2
                        },
                        new
                        {
                            Id = 223,
                            Name = "Manchester Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 224,
                            Name = "Maremma Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 225,
                            Name = "Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 226,
                            Name = "Minyatür Bull Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 227,
                            Name = "Minyatür Pinscher",
                            PetType = 2
                        },
                        new
                        {
                            Id = 228,
                            Name = "Minyatür Schnauzer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 229,
                            Name = "Mudi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 230,
                            Name = "Napoliten Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 231,
                            Name = "Newfoundland",
                            PetType = 2
                        },
                        new
                        {
                            Id = 232,
                            Name = "Norfolk Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 233,
                            Name = "Norrbottenspets",
                            PetType = 2
                        },
                        new
                        {
                            Id = 234,
                            Name = "Norsk Buhund",
                            PetType = 2
                        },
                        new
                        {
                            Id = 235,
                            Name = "Norveç Geyik Avcısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 236,
                            Name = "Norwich Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 237,
                            Name = "Old English Sheepdog",
                            PetType = 2
                        },
                        new
                        {
                            Id = 238,
                            Name = "Otterhound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 239,
                            Name = "Pappilon",
                            PetType = 2
                        },
                        new
                        {
                            Id = 240,
                            Name = "Pekingese",
                            PetType = 2
                        },
                        new
                        {
                            Id = 241,
                            Name = "Pembroke Welsh Corgi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 242,
                            Name = "Peru Tüysüz Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 243,
                            Name = "Petit Basset Griffon Vendien",
                            PetType = 2
                        },
                        new
                        {
                            Id = 244,
                            Name = "Petit Bleu de Gascogne",
                            PetType = 2
                        },
                        new
                        {
                            Id = 245,
                            Name = "Pharaoh Hound",
                            PetType = 2
                        },
                        new
                        {
                            Id = 246,
                            Name = "Picardy Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 247,
                            Name = "Plott Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 248,
                            Name = "Pointer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 249,
                            Name = "Poitevin",
                            PetType = 2
                        },
                        new
                        {
                            Id = 250,
                            Name = "Polonya Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 251,
                            Name = "Pomeranyalı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 252,
                            Name = "Poodle (Minyatür Kaniş)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 253,
                            Name = "Poodle(Standart Kaniş)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 254,
                            Name = "Portekiz Su Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 255,
                            Name = "Presa Canario",
                            PetType = 2
                        },
                        new
                        {
                            Id = 256,
                            Name = "Pug",
                            PetType = 2
                        },
                        new
                        {
                            Id = 257,
                            Name = "Puli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 258,
                            Name = "Pumi",
                            PetType = 2
                        },
                        new
                        {
                            Id = 259,
                            Name = "Pyrenees Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 260,
                            Name = "Pyrenees Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 261,
                            Name = "Rafeiro do Alentejo",
                            PetType = 2
                        },
                        new
                        {
                            Id = 262,
                            Name = "Rhodesian Ridgeback",
                            PetType = 2
                        },
                        new
                        {
                            Id = 263,
                            Name = "Rottweiler",
                            PetType = 2
                        },
                        new
                        {
                            Id = 264,
                            Name = "Russian Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 265,
                            Name = "Sakallı Collie",
                            PetType = 2
                        },
                        new
                        {
                            Id = 266,
                            Name = "Saluki",
                            PetType = 2
                        },
                        new
                        {
                            Id = 267,
                            Name = "Samoyed",
                            PetType = 2
                        },
                        new
                        {
                            Id = 268,
                            Name = "Sanshu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 269,
                            Name = "Schipperkee",
                            PetType = 2
                        },
                        new
                        {
                            Id = 270,
                            Name = "Sealyham Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 271,
                            Name = "Shetland Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 272,
                            Name = "Shiba Inu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 273,
                            Name = "Shih Tzu",
                            PetType = 2
                        },
                        new
                        {
                            Id = 274,
                            Name = "Sibirya Kurdu (Husky)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 275,
                            Name = "Silky Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 276,
                            Name = "Siyah ve Açık Kahverengi Rakun Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 277,
                            Name = "Skye Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 278,
                            Name = "Slovak Tchouvatch",
                            PetType = 2
                        },
                        new
                        {
                            Id = 279,
                            Name = "Soft Coated Wheaten Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 280,
                            Name = "Sokö (Sokak Köpeği)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 281,
                            Name = "St. Bernard (Saint Bernard)",
                            PetType = 2
                        },
                        new
                        {
                            Id = 282,
                            Name = "Staffordshire Bull Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 283,
                            Name = "Standart Schnauzer",
                            PetType = 2
                        },
                        new
                        {
                            Id = 284,
                            Name = "Steinbracke",
                            PetType = 2
                        },
                        new
                        {
                            Id = 285,
                            Name = "Styrian Dağ Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 286,
                            Name = "Sussex Spanieli",
                            PetType = 2
                        },
                        new
                        {
                            Id = 287,
                            Name = "Tatra Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 288,
                            Name = "Tibet Terrieri",
                            PetType = 2
                        },
                        new
                        {
                            Id = 289,
                            Name = "Tibetli Mastiff",
                            PetType = 2
                        },
                        new
                        {
                            Id = 290,
                            Name = "Tibetli Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 291,
                            Name = "Tosa",
                            PetType = 2
                        },
                        new
                        {
                            Id = 292,
                            Name = "Trigg Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 293,
                            Name = "Türk Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 294,
                            Name = "Tüysüz Collie",
                            PetType = 2
                        },
                        new
                        {
                            Id = 295,
                            Name = "Tyrolean Tazısı",
                            PetType = 2
                        },
                        new
                        {
                            Id = 296,
                            Name = "Valee Çoban Köpeği",
                            PetType = 2
                        },
                        new
                        {
                            Id = 297,
                            Name = "Vizsla",
                            PetType = 2
                        },
                        new
                        {
                            Id = 298,
                            Name = "Weimaraner",
                            PetType = 2
                        },
                        new
                        {
                            Id = 299,
                            Name = "Welsh Springer Spaniel",
                            PetType = 2
                        },
                        new
                        {
                            Id = 300,
                            Name = "Welsh Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 301,
                            Name = "West Highland White Terrier",
                            PetType = 2
                        },
                        new
                        {
                            Id = 302,
                            Name = "Westphalia Basseti",
                            PetType = 2
                        },
                        new
                        {
                            Id = 303,
                            Name = "Whippet",
                            PetType = 2
                        },
                        new
                        {
                            Id = 304,
                            Name = "Wirehaired Pointing Griffon",
                            PetType = 2
                        },
                        new
                        {
                            Id = 305,
                            Name = "Yorkshire Terrier",
                            PetType = 2
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("AccountId")
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("Created")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("Expires")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("Revoked")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Pet", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "AdoptedBy")
                        .WithMany()
                        .HasForeignKey("AdoptedById");

                    b.HasOne("WebApi.Entities.Account", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
